Is revert error
smartcontractkit/ccip-read pull request #22
Opened 2022-02-04 20:07 UTC by makoto

When I was testing against ropsten, the call was throwing an error and the original error was within `e.error.data.originalError.data`

2022-02-05 00:51 UTC, Arachnid requested changes

2022-02-05 00:51 UTC, Arachnid commented on packages/ethers-ccip-read-provider/src/index.ts
> +    let bytes: any;
This should be typed - probably `Uint8Array`.

2022-02-05 00:51 UTC, Arachnid commented on packages/ethers-ccip-read-provider/src/index.ts
> +      }
You need to rethrow this if the if clause returns false, or if it is a different revert.

2022-02-08 22:50 UTC, makoto commented
@Arachnid please take a look again

2022-02-14 21:45 UTC, Arachnid approved these changes

2022-02-14 21:45 UTC, Arachnid commented on packages/ethers-ccip-read-provider/src/index.ts
> +      bytes = arrayify(result);
```suggestion
    let bytes: Uint8Array;
    try {
      const result = await provider.parent.perform('call', params);
      bytes = arrayify(result);
```

2022-02-15 16:03 UTC, merged