cloudflare worker compatible ccip-read library
smartcontractkit/ccip-read pull request #29
Opened 2022-10-30 00:36 UTC by mdtanrikulu

[Given package](https://github.com/smartcontractkit/ccip-read/tree/mdt/cf-worker/packages/worker) is enabling users to develop cloudflare worker compatible ccip-read services, including [offchain-resolver gateway](https://github.com/ensdomains/offchain-resolver/tree/mdt/cf-worker/packages/gateway-worker).

After merge, aforementioned library is required to be published as a separate NPM package. 
(as @chainlink/ccip-read-cf-worker)

2023-01-09 06:26 UTC, cds95 requested changes
Looks good overall.  Just left some minor comments.

2023-01-09 06:26 UTC, cds95 commented on packages/worker/src/index.ts
> + * Implements a Durin gateway service using itty-router.js.
Rename `Durin` to `CCIP-Read`.

2023-01-09 06:26 UTC, cds95 commented on packages/worker/src/index.ts
> +    if (handler === undefined) {
Can probably just do `if (!handler)`.

2023-01-09 06:26 UTC, cds95 commented on packages/worker/src/index.ts
> +    const selector = calldata.slice(0, 10).toLowerCase();
It might be good to refactor this into a function named `getFunctionSelector(calldata: string)`.

2023-01-09 06:26 UTC, cds95 commented on packages/worker/tests/durin.test.ts
> +import 'isomorphic-fetch';
Rename this file into `ccipRead.test.ts`.

2023-01-09 06:26 UTC, cds95 commented on packages/worker/tests/durin.test.ts
> +describe('Durin', () => {
```suggestion
describe('CCIP-Read', () => {
```

2023-01-10 04:36 UTC, cds95 approved these changes

2023-01-10 04:36 UTC, cds95 commented
Changes LGTM but it looks like the build is failing.

2023-01-20 16:57 UTC, mdtanrikulu commented
There are couple of issues updating external libraries even in patch level. 

- Types of express are broken: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138
- Hardhat does not work with `npx` even though there is a local version installed.
- Any call to the contract was reverting without a reason


So I had to preserve yarn.lock as much as possible to not break any external compatibility.

2023-02-20 21:00 UTC, merged